services:
  filebrowser.api:
    image: ${DOCKER_REGISTRY-}filebrowserapi
    build:
      context: .
      dockerfile: src/FileBrowser.Api/Dockerfile
    ports:
      - "8001:8001"
    environment:
      ASPNETCORE_URLS: http://+:8001
      FileBrowser__HomeDirectory: /var/lib/filebrowser
    volumes:
      - ./local-storage:/var/lib/filebrowser


  postgres:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d filebrowser"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "15432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filebrowser
