@FileBrowser.Api_HostAddress = http://localhost:5065

GET {{FileBrowser.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{FileBrowser.Api_HostAddress}}/api/search/semantic?query=annual%20financial%20reports&limit=10
Accept: application/json

###
