<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <Compile Remove="local-storage\**" />
    <Content Remove="local-storage\**" />
    <EmbeddedResource Remove="local-storage\**" />
    <None Remove="local-storage\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileBrowser.Application\FileBrowser.Application.csproj" />
    <ProjectReference Include="..\FileBrowser.Infrastructure\FileBrowser.Infrastructure.csproj" />
  </ItemGroup>

</Project>
